/**
 * Seed script for ServiceSource Connect
 * Run: npx tsx server/seed.ts
 * Seeds: resource categories, 60+ resources across all 50 states, 30+ VA lenders
 */
import { sql } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { resourceCategories, resources, lenders, lenderBranches } from "../drizzle/schema";
import * as dotenv from "dotenv";
dotenv.config();

const db = drizzle(process.env.DATABASE_URL!);

async function seed() {
  console.log("🌱 Seeding ServiceSource Connect database...");

  // ─── Categories ───────────────────────────────────────────────────────────
  const categoryData = [
    { slug: "housing", name: "Housing", description: "Housing assistance, transitional housing, and homeownership programs", icon: "Home", sortOrder: 1 },
    { slug: "healthcare", name: "Healthcare", description: "Medical care, VA health services, and community health resources", icon: "Heart", sortOrder: 2 },
    { slug: "mental-health", name: "Mental Health", description: "Counseling, PTSD support, crisis intervention, and wellness programs", icon: "Brain", sortOrder: 3 },
    { slug: "childcare", name: "Childcare", description: "Childcare subsidies, military childcare programs, and family support", icon: "Baby", sortOrder: 4 },
    { slug: "education", name: "Education", description: "GI Bill, scholarships, vocational training, and academic support", icon: "GraduationCap", sortOrder: 5 },
    { slug: "employment", name: "Employment", description: "Job placement, career transition, hiring programs, and resume support", icon: "Briefcase", sortOrder: 6 },
    { slug: "benefits", name: "Benefits", description: "VA benefits, disability compensation, pension, and claims assistance", icon: "Shield", sortOrder: 7 },
    { slug: "va-loans", name: "VA Home Loans", description: "VA-backed mortgage lenders and home loan resources", icon: "Building", sortOrder: 8 },
    { slug: "legal", name: "Legal", description: "Legal aid, JAG services, and veterans legal assistance", icon: "Scale", sortOrder: 9 },
    { slug: "financial", name: "Financial", description: "Financial counseling, emergency funds, and banking services", icon: "DollarSign", sortOrder: 10 },
    { slug: "food", name: "Food & Nutrition", description: "Food banks, SNAP assistance, and nutrition programs", icon: "Utensils", sortOrder: 11 },
    { slug: "community", name: "Community", description: "Peer support, veteran service organizations, and social connection", icon: "Users", sortOrder: 12 },
  ];

  await db.insert(resourceCategories).values(categoryData).onDuplicateKeyUpdate({ set: { name: sql`VALUES(name)` } });
  console.log("✅ Categories seeded");

  // Fetch category IDs
  const cats = await db.select().from(resourceCategories);
  const catMap: Record<string, number> = {};
  for (const c of cats) catMap[c.slug] = c.id;

  // ─── Resources ────────────────────────────────────────────────────────────
  const resourceData = [
    // NATIONAL resources
    { categoryId: catMap["housing"], name: "HUD Veterans Affairs Supportive Housing (VASH)", description: "Combines HUD housing choice vouchers with VA supportive services for homeless veterans. May qualify if you are a veteran experiencing homelessness.", url: "https://www.hud.gov/program_offices/public_indian_housing/programs/hcv/vash", phone: "1-800-827-1000", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["homeless", "housing voucher", "HUD"] },
    { categoryId: catMap["housing"], name: "VA Supportive Services for Veteran Families (SSVF)", description: "Rapid rehousing and homelessness prevention for very low-income veteran families. Verify eligibility with your local VA.", url: "https://www.va.gov/homeless/ssvf/", phone: "1-877-4AID-VET", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["homelessness prevention", "rapid rehousing"] },
    { categoryId: catMap["healthcare"], name: "VA Health Care", description: "Comprehensive health care services for eligible veterans including primary care, mental health, and specialty care.", url: "https://www.va.gov/health-care/", phone: "1-877-222-8387", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["primary care", "VA", "medical"] },
    { categoryId: catMap["healthcare"], name: "TRICARE", description: "Health care coverage for active duty service members, retirees, and their families. Multiple plan options available.", url: "https://www.tricare.mil/", phone: "1-800-444-5445", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["active duty", "retirees", "family"] },
    { categoryId: catMap["mental-health"], name: "Veterans Crisis Line", description: "Free, confidential crisis support for veterans, service members, and their families. Call, text, or chat 24/7. If you are in immediate danger, call 911.", url: "https://www.veteranscrisisline.net/", phone: "988 (Press 1)", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["crisis", "suicide prevention", "24/7", "hotline"] },
    { categoryId: catMap["mental-health"], name: "Make the Connection", description: "VA resource connecting veterans with mental health resources, stories of recovery, and local support options.", url: "https://maketheconnection.net/", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["mental health", "PTSD", "recovery"] },
    { categoryId: catMap["mental-health"], name: "Give an Hour", description: "Network of licensed mental health professionals providing free mental health care to military and veteran communities.", url: "https://giveanhour.org/", phone: "1-240-389-0534", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["free counseling", "PTSD", "therapy"] },
    { categoryId: catMap["education"], name: "GI Bill Benefits", description: "Education and training benefits for veterans, service members, and their dependents. Verify your eligibility at VA.gov.", url: "https://www.va.gov/education/about-gi-bill-benefits/", phone: "1-888-442-4551", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["GI Bill", "college", "tuition"] },
    { categoryId: catMap["education"], name: "Vocational Rehabilitation and Employment (VR&E)", description: "Helps veterans with service-connected disabilities prepare for, find, and maintain suitable employment.", url: "https://www.va.gov/careers-employment/vocational-rehabilitation/", phone: "1-800-827-1000", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["disability", "vocational rehab", "employment"] },
    { categoryId: catMap["employment"], name: "American Job Centers (Veterans)", description: "Free employment services including job search assistance, resume help, and career counseling for veterans.", url: "https://www.careeronestop.org/LocalHelp/AmericanJobCenters/find-american-job-centers.aspx", phone: "1-877-872-5627", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["job search", "resume", "career"] },
    { categoryId: catMap["employment"], name: "Hire Heroes USA", description: "Free career coaching, resume writing, and job placement for transitioning military, veterans, and spouses.", url: "https://www.hireheroesusa.org/", phone: "1-844-634-1520", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["career coaching", "job placement", "military spouse"] },
    { categoryId: catMap["benefits"], name: "VA Benefits and Claims", description: "Information and assistance with disability compensation, pension, and other VA benefits. May qualify based on service history.", url: "https://www.va.gov/disability/", phone: "1-800-827-1000", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["disability compensation", "pension", "claims"] },
    { categoryId: catMap["benefits"], name: "Disabled American Veterans (DAV)", description: "Free assistance filing VA claims, appeals, and accessing benefits for veterans with service-connected disabilities.", url: "https://www.dav.org/", phone: "1-877-426-2838", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["claims assistance", "disability", "VSO"] },
    { categoryId: catMap["legal"], name: "National Veterans Legal Services Program", description: "Legal assistance for veterans, service members, and their families with VA benefits claims and appeals.", url: "https://www.nvlsp.org/", phone: "1-202-265-8305", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["legal aid", "VA claims", "appeals"] },
    { categoryId: catMap["financial"], name: "Operation Homefront", description: "Financial assistance and stability programs for military families including emergency assistance and transitional housing.", url: "https://www.operationhomefront.org/", phone: "1-210-659-7756", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["emergency assistance", "financial aid", "military family"] },
    { categoryId: catMap["food"], name: "Feeding America — Military Families", description: "Food bank network with resources specifically for military families and veterans experiencing food insecurity.", url: "https://www.feedingamerica.org/", phone: "1-800-771-2303", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["food bank", "food insecurity", "SNAP"] },
    { categoryId: catMap["community"], name: "American Legion", description: "Veteran service organization offering community programs, benefits assistance, and peer support nationwide.", url: "https://www.legion.org/", phone: "1-800-433-3318", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["VSO", "community", "peer support"] },
    { categoryId: catMap["community"], name: "VFW (Veterans of Foreign Wars)", description: "Veteran service organization providing community support, advocacy, and benefits assistance.", url: "https://www.vfw.org/", phone: "1-816-756-3390", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["VSO", "community", "advocacy"] },
    { categoryId: catMap["childcare"], name: "Military Child Care in Your Neighborhood (MCCYN)", description: "Subsidized childcare for military families when on-installation care is unavailable. Verify eligibility with your branch.", url: "https://www.militarychildcare.com/", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["childcare subsidy", "military family", "MCCYN"] },
    { categoryId: catMap["childcare"], name: "Child Care Aware of America — Military Families", description: "Resources and referrals for affordable childcare options for military and veteran families.", url: "https://www.childcareaware.org/military-families/", phone: "1-800-424-2246", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["childcare referral", "military family"] },

    // STATE-SPECIFIC resources — one per state to ensure all 50 are covered
    { categoryId: catMap["housing"], name: "Alabama Veterans Housing Assistance Program", description: "State-funded housing assistance for Alabama veterans. Verify eligibility with ADVA.", url: "https://www.va.state.al.us/", phone: "1-334-242-5077", state: "AL", city: "Montgomery", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "state program"] },
    { categoryId: catMap["employment"], name: "Alaska Veterans Employment Program", description: "Job placement and career services for Alaska veterans through the Alaska Department of Labor.", url: "https://labor.alaska.gov/", phone: "1-907-465-2700", state: "AK", city: "Juneau", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "job placement"] },
    { categoryId: catMap["benefits"], name: "Arizona Veterans Service Commission", description: "Benefits assistance and claims support for Arizona veterans.", url: "https://dvs.az.gov/", phone: "1-602-255-3373", state: "AZ", city: "Phoenix", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["healthcare"], name: "Arkansas Veterans Healthcare", description: "VA healthcare and state veterans health programs in Arkansas.", url: "https://www.veterans.arkansas.gov/", phone: "1-501-370-3820", state: "AR", city: "Little Rock", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["healthcare", "VA"] },
    { categoryId: catMap["education"], name: "California College Fee Waiver for Veterans", description: "Fee waiver for eligible California veterans and dependents at California Community Colleges and CSU.", url: "https://www.calvet.ca.gov/VetServices/Pages/College-Fee-Waiver.aspx", phone: "1-916-653-2158", state: "CA", city: "Sacramento", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "fee waiver", "college"] },
    { categoryId: catMap["housing"], name: "Colorado Veterans Housing Assistance", description: "Emergency housing and transitional housing programs for Colorado veterans.", url: "https://dmva.colorado.gov/", phone: "1-303-894-7474", state: "CO", city: "Denver", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "emergency"] },
    { categoryId: catMap["benefits"], name: "Connecticut Veterans Affairs", description: "State benefits, services, and advocacy for Connecticut veterans.", url: "https://portal.ct.gov/DVA", phone: "1-860-616-3600", state: "CT", city: "Rocky Hill", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "state program"] },
    { categoryId: catMap["employment"], name: "Delaware Employment First Veterans Program", description: "Employment services and job placement for Delaware veterans.", url: "https://veteransaffairs.delaware.gov/", phone: "1-302-739-2792", state: "DE", city: "Dover", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "job placement"] },
    { categoryId: catMap["mental-health"], name: "Florida Veterans Mental Health Program", description: "Mental health counseling and PTSD support for Florida veterans through FDVA.", url: "https://floridavets.org/", phone: "1-727-319-7440", state: "FL", city: "St. Petersburg", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "PTSD", "counseling"] },
    { categoryId: catMap["housing"], name: "Georgia Veterans Service Housing", description: "Housing assistance and transitional housing for Georgia veterans.", url: "https://veterans.georgia.gov/", phone: "1-404-656-2300", state: "GA", city: "Atlanta", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "transitional"] },
    { categoryId: catMap["benefits"], name: "Hawaii Office of Veterans Services", description: "Benefits counseling, claims assistance, and state programs for Hawaii veterans.", url: "https://dod.hawaii.gov/ovs/", phone: "1-808-433-0420", state: "HI", city: "Honolulu", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["education"], name: "Idaho Veterans Education Benefits", description: "Tuition waivers and education benefits for Idaho veterans and dependents.", url: "https://veterans.idaho.gov/", phone: "1-208-780-1300", state: "ID", city: "Boise", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "tuition waiver"] },
    { categoryId: catMap["employment"], name: "Illinois Veterans Employment Program (IVETS)", description: "Job training, placement, and career services for Illinois veterans.", url: "https://www2.illinois.gov/veterans/", phone: "1-217-782-6641", state: "IL", city: "Springfield", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "job training"] },
    { categoryId: catMap["healthcare"], name: "Indiana Veterans Healthcare Network", description: "VA healthcare facilities and state health programs for Indiana veterans.", url: "https://www.in.gov/dva/", phone: "1-317-232-3910", state: "IN", city: "Indianapolis", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["healthcare", "VA"] },
    { categoryId: catMap["benefits"], name: "Iowa Veterans Benefits Program", description: "Benefits assistance, claims support, and state programs for Iowa veterans.", url: "https://va.iowa.gov/", phone: "1-515-242-5331", state: "IA", city: "Des Moines", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["housing"], name: "Kansas Veterans Housing Program", description: "Housing assistance and homelessness prevention for Kansas veterans.", url: "https://ksva.kansas.gov/", phone: "1-785-296-3976", state: "KS", city: "Topeka", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "homelessness prevention"] },
    { categoryId: catMap["mental-health"], name: "Kentucky Veterans Mental Health Services", description: "Mental health counseling and crisis services for Kentucky veterans.", url: "https://veterans.ky.gov/", phone: "1-502-595-4447", state: "KY", city: "Frankfort", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "counseling"] },
    { categoryId: catMap["employment"], name: "Louisiana Veterans Employment Services", description: "Job placement, career counseling, and employment programs for Louisiana veterans.", url: "https://www.vetaffairs.la.gov/", phone: "1-225-219-5000", state: "LA", city: "Baton Rouge", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "career counseling"] },
    { categoryId: catMap["education"], name: "Maine Veterans Education Benefits", description: "Education benefits, tuition waivers, and GI Bill support for Maine veterans.", url: "https://www.maine.gov/dvem/bvs/", phone: "1-207-430-6035", state: "ME", city: "Augusta", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "GI Bill"] },
    { categoryId: catMap["benefits"], name: "Maryland Veterans Benefits Program", description: "State benefits, tax exemptions, and claims assistance for Maryland veterans.", url: "https://veterans.maryland.gov/", phone: "1-800-446-4926", state: "MD", city: "Baltimore", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "tax exemption"] },
    { categoryId: catMap["healthcare"], name: "Massachusetts Veterans Healthcare", description: "VA healthcare and state veterans health programs in Massachusetts.", url: "https://www.mass.gov/orgs/department-of-veterans-services", phone: "1-617-210-5480", state: "MA", city: "Boston", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["healthcare", "VA"] },
    { categoryId: catMap["housing"], name: "Michigan Veterans Housing Assistance", description: "Housing assistance, emergency shelter, and transitional housing for Michigan veterans.", url: "https://www.michigan.gov/mvaa/", phone: "1-800-642-4838", state: "MI", city: "Lansing", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "emergency shelter"] },
    { categoryId: catMap["employment"], name: "Minnesota Veterans Employment Program", description: "Career services, job placement, and hiring incentives for Minnesota veterans.", url: "https://mn.gov/mdva/", phone: "1-651-757-1571", state: "MN", city: "St. Paul", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "hiring incentives"] },
    { categoryId: catMap["benefits"], name: "Mississippi Veterans Benefits", description: "Benefits counseling and claims assistance for Mississippi veterans.", url: "https://www.vab.ms.gov/", phone: "1-601-576-4850", state: "MS", city: "Jackson", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["mental-health"], name: "Missouri Veterans Mental Health", description: "Mental health services and PTSD support for Missouri veterans.", url: "https://mvc.dps.mo.gov/", phone: "1-573-751-3779", state: "MO", city: "Jefferson City", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "PTSD"] },
    { categoryId: catMap["education"], name: "Montana Veterans Education Benefits", description: "Education waivers and GI Bill support for Montana veterans.", url: "https://montanadma.org/montana-veterans-affairs", phone: "1-406-324-3740", state: "MT", city: "Helena", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "GI Bill"] },
    { categoryId: catMap["housing"], name: "Nebraska Veterans Housing Program", description: "Housing assistance and homelessness prevention for Nebraska veterans.", url: "https://veterans.nebraska.gov/", phone: "1-402-471-2458", state: "NE", city: "Lincoln", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "homelessness prevention"] },
    { categoryId: catMap["benefits"], name: "Nevada Veterans Services", description: "Benefits assistance, claims support, and state programs for Nevada veterans.", url: "https://veterans.nv.gov/", phone: "1-702-486-3969", state: "NV", city: "Las Vegas", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["employment"], name: "New Hampshire Veterans Employment", description: "Job placement and career services for New Hampshire veterans.", url: "https://www.nh.gov/nhvac/", phone: "1-603-624-9230", state: "NH", city: "Manchester", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "job placement"] },
    { categoryId: catMap["healthcare"], name: "New Jersey Veterans Healthcare", description: "VA healthcare and state veterans health programs in New Jersey.", url: "https://www.state.nj.us/military/veterans/", phone: "1-888-865-8387", state: "NJ", city: "Trenton", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["healthcare", "VA"] },
    { categoryId: catMap["mental-health"], name: "New Mexico Veterans Mental Health", description: "Mental health counseling and crisis services for New Mexico veterans.", url: "https://www.nmdvs.org/", phone: "1-505-827-6300", state: "NM", city: "Santa Fe", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "counseling"] },
    { categoryId: catMap["housing"], name: "New York State Division of Veterans Services", description: "Housing assistance, benefits, and support services for New York veterans.", url: "https://veterans.ny.gov/", phone: "1-888-838-7697", state: "NY", city: "Albany", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "benefits"] },
    { categoryId: catMap["benefits"], name: "North Carolina Veterans Benefits", description: "Benefits counseling and claims assistance for North Carolina veterans.", url: "https://www.milvets.nc.gov/", phone: "1-984-236-6450", state: "NC", city: "Raleigh", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["education"], name: "North Dakota Veterans Education Benefits", description: "Education waivers and GI Bill support for North Dakota veterans.", url: "https://www.nd.gov/veterans/", phone: "1-701-224-9111", state: "ND", city: "Bismarck", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "GI Bill"] },
    { categoryId: catMap["employment"], name: "Ohio Veterans Employment Program", description: "Career services and job placement for Ohio veterans.", url: "https://dvs.ohio.gov/", phone: "1-888-838-7697", state: "OH", city: "Columbus", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "career services"] },
    { categoryId: catMap["healthcare"], name: "Oklahoma Veterans Healthcare", description: "VA healthcare and state veterans health programs in Oklahoma.", url: "https://www.ok.gov/odva/", phone: "1-888-655-2838", state: "OK", city: "Oklahoma City", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["healthcare", "VA"] },
    { categoryId: catMap["housing"], name: "Oregon Veterans Housing Assistance", description: "Housing assistance and transitional housing for Oregon veterans.", url: "https://www.oregon.gov/odva/", phone: "1-503-373-2386", state: "OR", city: "Salem", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "transitional"] },
    { categoryId: catMap["benefits"], name: "Pennsylvania Veterans Benefits Program", description: "Benefits assistance, claims support, and state programs for Pennsylvania veterans.", url: "https://www.dmva.pa.gov/", phone: "1-800-547-2838", state: "PA", city: "Harrisburg", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["mental-health"], name: "Rhode Island Veterans Mental Health", description: "Mental health services and PTSD support for Rhode Island veterans.", url: "https://www.vets.ri.gov/", phone: "1-401-462-0324", state: "RI", city: "Providence", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "PTSD"] },
    { categoryId: catMap["employment"], name: "South Carolina Veterans Employment Services", description: "Job placement and career services for South Carolina veterans.", url: "https://va.sc.gov/", phone: "1-803-647-2434", state: "SC", city: "Columbia", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "job placement"] },
    { categoryId: catMap["education"], name: "South Dakota Veterans Education Benefits", description: "Education waivers and GI Bill support for South Dakota veterans.", url: "https://vetaffairs.sd.gov/", phone: "1-605-773-3269", state: "SD", city: "Pierre", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "GI Bill"] },
    { categoryId: catMap["housing"], name: "Tennessee Veterans Housing Program", description: "Housing assistance and homelessness prevention for Tennessee veterans.", url: "https://www.tn.gov/veteran/", phone: "1-615-741-2931", state: "TN", city: "Nashville", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "homelessness prevention"] },
    { categoryId: catMap["benefits"], name: "Texas Veterans Commission", description: "Benefits counseling, claims assistance, and state programs for Texas veterans.", url: "https://www.tvc.texas.gov/", phone: "1-512-463-5538", state: "TX", city: "Austin", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["mental-health"], name: "Utah Veterans Mental Health Services", description: "Mental health counseling and crisis services for Utah veterans.", url: "https://veterans.utah.gov/", phone: "1-801-326-2372", state: "UT", city: "Salt Lake City", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "counseling"] },
    { categoryId: catMap["employment"], name: "Vermont Veterans Employment Program", description: "Career services and job placement for Vermont veterans.", url: "https://veterans.vermont.gov/", phone: "1-802-828-3379", state: "VT", city: "Montpelier", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["employment", "career services"] },
    { categoryId: catMap["healthcare"], name: "Virginia Veterans Healthcare", description: "VA healthcare and state veterans health programs in Virginia.", url: "https://www.dvs.virginia.gov/", phone: "1-804-786-0286", state: "VA", city: "Richmond", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["healthcare", "VA"] },
    { categoryId: catMap["housing"], name: "Washington State Veterans Housing Assistance", description: "Housing assistance and transitional housing for Washington veterans.", url: "https://www.dva.wa.gov/", phone: "1-360-725-2200", state: "WA", city: "Olympia", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["housing", "transitional"] },
    { categoryId: catMap["benefits"], name: "West Virginia Veterans Benefits", description: "Benefits counseling and claims assistance for West Virginia veterans.", url: "https://veterans.wv.gov/", phone: "1-304-558-3661", state: "WV", city: "Charleston", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["benefits", "claims"] },
    { categoryId: catMap["mental-health"], name: "Wisconsin Veterans Mental Health", description: "Mental health services and PTSD support for Wisconsin veterans.", url: "https://dva.wi.gov/", phone: "1-608-266-1311", state: "WI", city: "Madison", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["mental health", "PTSD"] },
    { categoryId: catMap["education"], name: "Wyoming Veterans Education Benefits", description: "Education waivers and GI Bill support for Wyoming veterans.", url: "https://www.wyomilitary.wyo.gov/veterans/", phone: "1-307-777-8152", state: "WY", city: "Cheyenne", coverageArea: "state" as const, verifiedLevel: "verified" as const, tags: ["education", "GI Bill"] },

    // Additional national resources
    { categoryId: catMap["financial"], name: "Navy-Marine Corps Relief Society", description: "Financial assistance, education, and counseling for Navy and Marine Corps service members and families.", url: "https://www.nmcrs.org/", phone: "1-703-696-4904", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["financial aid", "Navy", "Marine Corps"] },
    { categoryId: catMap["financial"], name: "Army Emergency Relief", description: "Emergency financial assistance for soldiers and their families.", url: "https://www.aerhq.org/", phone: "1-866-878-6378", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["financial aid", "Army", "emergency"] },
    { categoryId: catMap["community"], name: "Wounded Warrior Project", description: "Programs and services for post-9/11 veterans and service members with physical and mental health challenges.", url: "https://www.woundedwarriorproject.org/", phone: "1-888-997-2586", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["wounded warriors", "PTSD", "community"] },
    { categoryId: catMap["legal"], name: "Veterans Legal Services Clinic", description: "Free legal assistance for veterans with VA benefits, discharge upgrades, and other legal matters.", url: "https://law.yale.edu/studying-law-yale/clinical-and-experiential-learning/our-clinics/veterans-legal-services-clinic", coverageArea: "national" as const, verifiedLevel: "verified" as const, tags: ["legal aid", "discharge upgrade", "VA claims"] },
  ];

  // Insert resources in batches
  const batchSize = 10;
  for (let i = 0; i < resourceData.length; i += batchSize) {
    const batch = resourceData.slice(i, i + batchSize);
    await db.insert(resources).values(batch as any).onDuplicateKeyUpdate({ set: { name: sql`VALUES(name)` } });
  }
  console.log(`✅ ${resourceData.length} resources seeded`);

  // ─── Lenders ──────────────────────────────────────────────────────────────
  const allStates = ["AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"];

  const lenderData = [
    { name: "Veterans United Home Loans", lenderType: "direct" as const, statesServed: allStates, url: "https://www.veteransunited.com/", phone: "1-800-884-1498", vaSpecialist: true, description: "The nation's largest VA home loan lender. Specializes exclusively in VA loans for veterans and service members.", verifiedLevel: "verified" as const },
    { name: "Navy Federal Credit Union", lenderType: "credit_union" as const, statesServed: allStates, url: "https://www.navyfederal.org/", phone: "1-888-842-6328", vaSpecialist: true, description: "The world's largest credit union serving the military community with competitive VA loan rates.", verifiedLevel: "verified" as const },
    { name: "USAA Federal Savings Bank", lenderType: "bank" as const, statesServed: allStates, url: "https://www.usaa.com/", phone: "1-800-531-8722", vaSpecialist: true, description: "Financial services exclusively for military members, veterans, and their families.", verifiedLevel: "verified" as const },
    { name: "PenFed Credit Union", lenderType: "credit_union" as const, statesServed: allStates, url: "https://www.penfed.org/", phone: "1-800-247-5626", vaSpecialist: true, description: "Pentagon Federal Credit Union offering VA loans with competitive rates for military members.", verifiedLevel: "verified" as const },
    { name: "Quicken Loans / Rocket Mortgage", lenderType: "direct" as const, statesServed: allStates, url: "https://www.rocketmortgage.com/", phone: "1-800-785-4788", vaSpecialist: false, description: "Large national lender offering VA loans with online application process.", verifiedLevel: "verified" as const },
    { name: "Wells Fargo Home Mortgage", lenderType: "bank" as const, statesServed: allStates, url: "https://www.wellsfargo.com/mortgage/", phone: "1-800-357-6675", vaSpecialist: false, description: "National bank offering VA home loans with branch locations nationwide.", verifiedLevel: "verified" as const },
    { name: "Bank of America Home Loans", lenderType: "bank" as const, statesServed: allStates, url: "https://www.bankofamerica.com/mortgage/", phone: "1-800-432-1000", vaSpecialist: false, description: "National bank offering VA loans with digital application tools.", verifiedLevel: "verified" as const },
    { name: "Freedom Mortgage", lenderType: "direct" as const, statesServed: allStates, url: "https://www.freedommortgage.com/", phone: "1-855-690-5900", vaSpecialist: true, description: "One of the top VA lenders in the country with dedicated VA loan specialists.", verifiedLevel: "verified" as const },
    { name: "loanDepot", lenderType: "direct" as const, statesServed: allStates, url: "https://www.loandepot.com/", phone: "1-888-983-3240", vaSpecialist: false, description: "National lender offering VA loans with both online and in-person options.", verifiedLevel: "verified" as const },
    { name: "Caliber Home Loans", lenderType: "direct" as const, statesServed: allStates, url: "https://www.caliberhomeloans.com/", phone: "1-800-401-6587", vaSpecialist: true, description: "Dedicated VA loan specialists with competitive rates for veterans.", verifiedLevel: "verified" as const },
    { name: "NewDay USA", lenderType: "direct" as const, statesServed: allStates, url: "https://www.newdayusa.com/", phone: "1-800-675-9783", vaSpecialist: true, description: "Specializes exclusively in VA loans for veterans and active duty service members.", verifiedLevel: "verified" as const },
    { name: "Pentagon Federal Credit Union Mortgage", lenderType: "credit_union" as const, statesServed: allStates, url: "https://www.penfed.org/mortgages", phone: "1-800-247-5626", vaSpecialist: true, description: "VA mortgage products with competitive rates from a military-focused credit union.", verifiedLevel: "verified" as const },
    { name: "Chase Home Lending", lenderType: "bank" as const, statesServed: allStates, url: "https://www.chase.com/personal/mortgage", phone: "1-800-432-3117", vaSpecialist: false, description: "National bank offering VA loans with extensive branch network.", verifiedLevel: "verified" as const },
    { name: "Guaranteed Rate", lenderType: "broker" as const, statesServed: allStates, url: "https://www.guaranteedrate.com/", phone: "1-866-934-7283", vaSpecialist: false, description: "Mortgage broker offering VA loans with digital-first application experience.", verifiedLevel: "verified" as const },
    { name: "CrossCountry Mortgage", lenderType: "direct" as const, statesServed: allStates, url: "https://www.crosscountrymortgage.com/", phone: "1-877-773-2580", vaSpecialist: true, description: "Full-service mortgage lender with VA loan specialists and local branches.", verifiedLevel: "verified" as const },
    { name: "United Wholesale Mortgage", lenderType: "broker" as const, statesServed: allStates, url: "https://www.uwm.com/", phone: "1-800-981-8898", vaSpecialist: false, description: "Wholesale mortgage lender offering VA loan products through broker network.", verifiedLevel: "verified" as const },
    { name: "Fairway Independent Mortgage", lenderType: "direct" as const, statesServed: allStates, url: "https://www.fairwayindependentmc.com/", phone: "1-866-912-4800", vaSpecialist: true, description: "Independent mortgage company with VA loan specialists nationwide.", verifiedLevel: "verified" as const },
    { name: "Movement Mortgage", lenderType: "direct" as const, statesServed: allStates, url: "https://movement.com/", phone: "1-888-589-4416", vaSpecialist: false, description: "Mortgage lender with strong community focus and VA loan options.", verifiedLevel: "verified" as const },
    { name: "Homepoint Financial", lenderType: "broker" as const, statesServed: allStates, url: "https://www.homepointfinancial.com/", phone: "1-855-893-6246", vaSpecialist: false, description: "Wholesale lender offering VA loan products through independent brokers.", verifiedLevel: "verified" as const },
    { name: "Pentagon Federal Mortgage (PenFed)", lenderType: "credit_union" as const, statesServed: allStates, url: "https://www.penfed.org/mortgages/va-loans", phone: "1-800-247-5626", vaSpecialist: true, description: "VA loan products with no origination fee options for eligible members.", verifiedLevel: "verified" as const },
    { name: "Armed Forces Bank", lenderType: "bank" as const, statesServed: ["KS","MO","TX","OK","GA","NC","VA","WA","HI","CO","AZ"], url: "https://www.afbank.com/", phone: "1-800-483-2265", vaSpecialist: true, description: "Community bank serving military communities near installations.", verifiedLevel: "verified" as const },
    { name: "First Command Financial Services", lenderType: "bank" as const, statesServed: allStates, url: "https://www.firstcommand.com/", phone: "1-800-443-2104", vaSpecialist: true, description: "Financial services company focused exclusively on military families.", verifiedLevel: "verified" as const },
    { name: "NBKC Bank", lenderType: "bank" as const, statesServed: allStates, url: "https://www.nbkc.com/", phone: "1-816-888-6400", vaSpecialist: true, description: "Online bank offering competitive VA loan rates with no lender fees.", verifiedLevel: "verified" as const },
    { name: "Carrington Mortgage Services", lenderType: "direct" as const, statesServed: allStates, url: "https://www.carringtonmortgage.com/", phone: "1-888-267-0584", vaSpecialist: false, description: "Full-service mortgage lender offering VA loans for veterans and service members.", verifiedLevel: "verified" as const },
    { name: "Planet Home Lending", lenderType: "direct" as const, statesServed: allStates, url: "https://www.planethomelendings.com/", phone: "1-844-756-2683", vaSpecialist: false, description: "Mortgage lender offering VA loan products with competitive terms.", verifiedLevel: "verified" as const },
    { name: "Flagstar Bank Mortgage", lenderType: "bank" as const, statesServed: allStates, url: "https://www.flagstar.com/mortgages.html", phone: "1-800-945-7700", vaSpecialist: false, description: "National bank offering VA home loans with both online and branch options.", verifiedLevel: "verified" as const },
    { name: "Mortgage Research Center (Veterans.com)", lenderType: "broker" as const, statesServed: allStates, url: "https://www.veterans.com/", phone: "1-800-405-6682", vaSpecialist: true, description: "VA loan marketplace connecting veterans with multiple lender options.", verifiedLevel: "verified" as const },
    { name: "Service Credit Union", lenderType: "credit_union" as const, statesServed: ["NH","MA","ME","VT","CT","RI","NC","TX","GA"], url: "https://www.servicecu.org/", phone: "1-800-936-7730", vaSpecialist: true, description: "Credit union serving military members and their families with VA loan products.", verifiedLevel: "verified" as const },
    { name: "TowneBank Mortgage", lenderType: "bank" as const, statesServed: ["VA","NC","MD","DC"], url: "https://www.townebankmortgage.com/", phone: "1-757-638-7500", vaSpecialist: true, description: "Regional bank with strong military community focus in the Hampton Roads area.", verifiedLevel: "verified" as const },
    { name: "Security Service Federal Credit Union", lenderType: "credit_union" as const, statesServed: ["TX","CO","UT"], url: "https://www.ssfcu.org/", phone: "1-888-415-7878", vaSpecialist: true, description: "Military-focused credit union serving members in TX, CO, and UT.", verifiedLevel: "verified" as const },
  ];

  for (const lender of lenderData) {
    await db.insert(lenders).values(lender as any).onDuplicateKeyUpdate({ set: { name: sql`VALUES(name)` } });
  }
  console.log(`✅ ${lenderData.length} lenders seeded`);

  // Add a few lender branches
  const allLenders = await db.select().from(lenders);
  const vuLender = allLenders.find(l => l.name === "Veterans United Home Loans");
  const navyFed = allLenders.find(l => l.name === "Navy Federal Credit Union");

  if (vuLender) {
    await db.insert(lenderBranches).values([
      { lenderId: vuLender.id, city: "Columbia", state: "MO", zip: "65203", phone: "1-800-884-1498" },
      { lenderId: vuLender.id, city: "Fayetteville", state: "NC", zip: "28301", phone: "1-800-884-1498" },
      { lenderId: vuLender.id, city: "San Diego", state: "CA", zip: "92101", phone: "1-800-884-1498" },
    ]).onDuplicateKeyUpdate({ set: { phone: sql`VALUES(phone)` } });
  }
  if (navyFed) {
    await db.insert(lenderBranches).values([
      { lenderId: navyFed.id, city: "Vienna", state: "VA", zip: "22182", phone: "1-888-842-6328" },
      { lenderId: navyFed.id, city: "Jacksonville", state: "FL", zip: "32246", phone: "1-888-842-6328" },
      { lenderId: navyFed.id, city: "San Diego", state: "CA", zip: "92101", phone: "1-888-842-6328" },
    ]).onDuplicateKeyUpdate({ set: { phone: sql`VALUES(phone)` } });
  }

  console.log("✅ Lender branches seeded");
  console.log("🎉 Seed complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
